name: isad_app
description: Ration Manager App
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^1.2.0

flutter:
  uses-material-design: true
